# Generated by Django 5.1.6 on 2025-03-04 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_login_password_remove_login_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
