# Generated by Django 5.1.6 on 2025-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
