# Generated by Django 5.1.6 on 2025-03-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_login_login_time_remove_login_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='email',
        ),
    ]
